# Generated by Django 3.0 on 2020-08-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorem',
            name='theorem_type',
            field=models.CharField(choices=[('L', 'Lemma'), ('C', 'Corollary'), ('P', 'Proposition'), ('T', 'Theorem')], default='T', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='definition',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='theorem',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
