# Generated by Django 3.0 on 2020-08-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0003_auto_20200815_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathematicalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='theorem',
            name='included_definitions',
        ),
        migrations.DeleteModel(
            name='Definition',
        ),
        migrations.AddField(
            model_name='theorem',
            name='included_objects',
            field=models.ManyToManyField(to='mathwiki.MathematicalObject'),
        ),
    ]
