# Generated by Django 3.0 on 2020-08-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0005_auto_20200815_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathematicalobject',
            name='contained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathwiki.MathematicalObject'),
        ),
        migrations.RemoveField(
            model_name='mathematicalobject',
            name='contains',
        ),
        migrations.AddField(
            model_name='mathematicalobject',
            name='contains',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Contained In +', to='mathwiki.MathematicalObject'),
        ),
        migrations.AlterField(
            model_name='mathematicalobject',
            name='parent_objects',
            field=models.ManyToManyField(blank=True, related_name='_mathematicalobject_parent_objects_+', to='mathwiki.MathematicalObject'),
        ),
        migrations.AlterField(
            model_name='mathematicalobject',
            name='properties',
            field=models.ManyToManyField(blank=True, to='mathwiki.MathematicalProperty'),
        ),
    ]
