# Generated by Django 3.0 on 2020-08-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0006_auto_20200815_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathematicalobject',
            name='contains',
        ),
        migrations.AddField(
            model_name='mathematicalobject',
            name='contains',
            field=models.ManyToManyField(blank=True, null=True, related_name='_mathematicalobject_contains_+', to='mathwiki.MathematicalObject'),
        ),
    ]
