# Generated by Django 3.0 on 2020-08-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0007_auto_20200815_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathematicalobject',
            name='contained_by',
        ),
        migrations.AlterField(
            model_name='mathematicalobject',
            name='contains',
            field=models.ManyToManyField(blank=True, related_name='_mathematicalobject_contains_+', to='mathwiki.MathematicalObject'),
        ),
        migrations.RemoveField(
            model_name='mathematicalobject',
            name='parent_objects',
        ),
        migrations.AddField(
            model_name='mathematicalobject',
            name='parent_objects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathwiki.MathematicalObject'),
        ),
    ]
