# Generated by Django 3.0 on 2020-08-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0008_auto_20200815_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='axiom',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mathematicalobject',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mathematicalproperty',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theorem',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
