# Generated by Django 3.0 on 2020-08-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0010_auto_20200816_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorem',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theorem',
            name='hypothesis',
            field=models.TextField(blank=True),
        ),
    ]
