# Generated by Django 3.0 on 2020-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathwiki', '0011_auto_20200823_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='axiom',
            name='examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mathematicalobject',
            name='examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mathematicalproperty',
            name='examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theorem',
            name='examples',
            field=models.TextField(blank=True),
        ),
    ]
